### ISSUE TITLE
why not use futures-io instead of custome io.

### ISSUE THREAD

**Issue by zmlzm** [quininer/ritsu#11]
I think this project is exicting! , but why not use futures-io instead of custome io?
it will be a problem.

**Comment by quininer** [comment]
In order to ensure memory security, we need to make future hold buffer ownership. This means that we cannot use `futures_io::Async{Read,Write}` or `tokio::io::Async{Read,Write}`.

see https://github.com/quininer/ritsu/issues/2

**Comment by zmlzm** [comment]
sure I believe it has reason, I only think it will be a problem for the project's future and rust ecosystem. Does't mean to criticize it
