### ISSUE TITLE
Fix Timer

### ISSUE THREAD

**Issue by quininer** [quininer/ritsu#13]
The current implementation of Timer cannot delay enough time, we may need to use timerfd.

**Comment by CarterLi** [comment]
You mean IORING_OP_TIMEOUT won't delay enough time? What's the problem?

**Comment by quininer** [comment]
>  off may contain a completion event count. If not set, this defaults to 1. A timeout will trigger a wakeup event on the completion ring for anyone waiting for events. A timeout condition is met when either the specified timeout expires, or the specified number of events have completed.

We don't want completed events to affect timeout.

**Comment by CarterLi** [comment]
you may set off=0

https://github.com/axboe/liburing/issues/18

**Comment by quininer** [comment]
Ha, this is very useful! I think the document of `liburing` needs to be updated.

**Comment by CarterLi** [comment]
never trust the document. source code is the best document.

**Comment by quininer** [comment]
Thank for your help.
